### ISSUE TITLE
Tables is not created automatically

### ISSUE THREAD

**Issue by ezsock5** [buggins/hibernated#19]
class Card
{
	import hibernated.core;
	
	@Id
	@Generated
	long id;
	@UniqueKey
	string pwd;
}

	MySQLDriver driver = new MySQLDriver();
	string url = MySQLDriver.generateUrl("10.211.55.10", 3306, "test");
	string[string] params = MySQLDriver.setUserAndPassword("root", "xxx");
	auto ds = new ConnectionPoolDataSourceImpl(driver, url, params);
	
	EntityMetaData schema = new SchemaInfoImpl!(Card); 
	Dialect dialect = new MySQLDialect();
	auto factory = new SessionFactoryImpl(schema, dialect, ds);

	
	Card c = new Card;
	auto s = factory.openSession();
	scope(exit) s.close();
	s.save(c);

my dub.json

{
	"name": "ezsockacount",
	"description": "A simple vibe.d server application.",
	"copyright": "Copyright © 2015, zhmt",
	"authors": ["zhmt"],
	"dependencies": {
		"vibe-d": ">=0.7.22",
		"mysql-native": "0.1.0",
		"hibernated": "0.2.19",
		"ddbc": ">=0.2.16"
	},
	"subConfigurations": {
		"hibernated": "MySQL",
		"ddbc": "MySQL"
	},
	"versions": ["VibeDefaultMain","USE_MYSQL"]
}

It compiles well, but throw an exception while running:
hibernated.type.MappingException@../../../zhmt/.dub/packages/hibernated-0.2.19/source/hibernated/metadata.d(3332): Cannot find entity by class app.Card

Can you help me?

**Comment by ezsock5** [comment]
I checked the "static EntityInfo [] entities; in SchemaInfoImpl" while running,
the length of entites is 0.

**Comment by buggins** [comment]
There is no automatic creation of schema, but it's possible to do it with minimal effort.
        DBInfo db = new DBInfo(dialect, schema);
        string[] createTables = db.getCreateTableSQL();
        string[] createIndexes = db.getCreateIndexSQL();
// then iterate by createTables and createIndexes and execute these queries.

**Comment by buggins** [comment]
Sorry, there is DBInfo.updateDBSchema(Connection conn, bool dropTables, bool createTables) which could be used for that

**Comment by buggins** [comment]
// Working solution:
// get connection
Connection conn = ds.getConnection();
scope(exit) conn.close();
// create tables if not exist
factory.getDBMetaData().updateDBSchema(conn, false, true);

**Comment by buggins** [comment]
Added this code to README

**Comment by aferust** [comment]
Hey this is closed, but I have discovered something. If one uses the library with vibed and version VibeDefaultMain (no main, entry point is module constructor), this happens: "Cannot find entity by class app.User". With a regular main function and no VibeDefaultMain, everything seems working.
