### ISSUE TITLE
not working with latest dmd (v2.069.2)

### ISSUE THREAD

**Issue by SingingBush** [buggins/hibernated#25]
I had to updatd my version of dmd due to min requirements of another dependency in my project but unfortunately updating dmd has caused hibernated to stop working. Is there any work on this at the moment?

**Comment by dueksam** [comment]
You can try to add this to your dub.json file:

"buildRequirements" : ["allowWarnings"]

Worked for me.

**Comment by SingingBush** [comment]
@dueksam thanks for that. Got the build working again. It's a shame that the compiler output didn't make it more obvious that the warnings were the reason for failure. 

Do you know if it's possible for me to _silence_ the warnings for hibernated whilst still getting the warnings for my code?

**Comment by buggins** [comment]
Not sure how to fix warnings properly.

**Comment by buggins** [comment]
Fixed.
