### ISSUE TITLE
v0.2.33 is broken

### ISSUE THREAD

**Issue by SingingBush** [buggins/hibernated#46]
I am using:

DMD64 D Compiler v2.072.0
DUB version 1.0.0, built on Oct 31 2016

```
.dub/packages/hibernated-0.2.33/hibernated/source/hibernated/core.d(29,15): Error: module ddbc is in file 'ddbc.d' which cannot be read
```

Please ensure travis builds are ok before doing a release. Version 0.2.29 was the last version on dub repo that's usable (along with ddbc 0.2.29).

See travis [build history](https://travis-ci.org/buggins/hibernated/builds) logs:

```
source/htestmain.d(52,22): Error: undefined identifier 'SQLITEDriver'
```

**Comment by buggins** [comment]
Did you try to `dub upgrade` ?

**Comment by SingingBush** [comment]
`dub upgrade` doesn't fix build. there is `Error: undefined identifier 'MySQLDriver'` as well as `Error: undefined identifier 'SQLITEDriver'`. 

I'm using the full config:

```
ddbc 0.3.2: building configuration "full"...
hibernated 0.2.33: building configuration "full"...
```

**Comment by eresid** [comment]
@SingingBush use import:
`import ddbc.drivers.sqliteddbc;`

**Comment by SingingBush** [comment]
no longer an issue
