### ISSUE TITLE
example1 fails to compile with:- Error: module std.traits import 'Filter' not found

### ISSUE THREAD

**Issue by rascala** [buggins/hibernated#52]
Running dub in examples/example1 folder gives an error:
`../../source/hibernated/metadata.d(841,12): Error: module std.traits import 'Filter' not found`

Operating System: `osx MacOS Sierra 10.12.6`
Using dmd and dub versions:
`⋊> ~/.../e/example1 on master ⨯ dub --version`
`DUB version 1.5.0, built on Sep  1 2017`

`⋊> ~/.../e/example1 on master ⨯ dmd --version`
`DMD64 D Compiler v2.076.0`

Fixed by changing
source/hibernated/metadata.d line:841
`import std.traits : FieldTypeTuple, Filter;`
to
` import std.traits : FieldTypeTuple;`
` import std.meta : Filter;`

**Comment by SingingBush** [comment]
Closing this as Hibernated currently supports the following D versions:

  - 2.087.0
  - 2.086.1
  - 2.085.1
  - 2.084.1
  - 2.083.1
  - 2.082.1

**Comment by SingingBush** [comment]
I actually had a local branch with following in it:

```D
    static if (__VERSION__ < 2074) {
        import std.traits : FieldTypeTuple, Filter; // Filter used to be in std.traits
    } else {
        import std.traits : FieldTypeTuple;
        import std.meta : Filter;
    }
```

although it's a pretty old D version it's worth pushing the fix. It'll be in next release
