### ISSUE TITLE
Fails with MappingException in a multithreaded environment

### ISSUE THREAD

**Issue by ximion** [buggins/hibernated#55]
Hi!
When using Hibernated in an environment with multiple threads, occasionally the following error is raised:
```hibernated.type.MappingException@/hibernated/hibernated/metadata.d(3375): Cannot find entity by name MyEntity```
(with `MyEntity` being whatever entity I want to deal with at that time).

From looking at the code, this should actually work in a multithreaded environment, so I don't really know what the problem is at time.

**Comment by TheWeirdDev** [comment]
I can reproduce this bug. Any idea why it happens?
