### ISSUE TITLE
Add support for SysTime type

### ISSUE THREAD

**Issue by muffledSheep** [buggins/hibernated#56]
It would nice if there was support for `std.datetime.systime.SysTime`. Thanks.

**Comment by bausshf** [comment]
It doesn't make much sense to use **SysTime**, but rather **DateTime** should be used.

**SysTime** is meant to represent a given time from the system ex. `Clock.currTime()` where as **DateTime** is meant to represent a user-specified time.

Could you give a scenario in which you it's preferred to use **SysTime** over **DateTime**?

**Comment by muffledSheep** [comment]
I'm glad to see this repo getting some attention after a while.
I use SysTime for internationalisation - DateTime has no concept of timezones as far a I know.

**Comment by SingingBush** [comment]
ddbc is where this kind of work is done. See related: https://github.com/buggins/ddbc/issues/62
