### ISSUE TITLE
Deprecation: std.exception.enforceEx

### ISSUE THREAD

**Issue by dangbinghoo** [buggins/hibernated#60]
Deprecation warning when building with 'DMD64 D Compiler v2.082.0'

`../../source/hibernated/metadata.d(307,35): Deprecation: function `std.exception.enforceEx!(MappingException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.
../../source/hibernated/query.d(93,38): Deprecation: function `std.exception.enforceEx!(HibernatedException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.
../../source/hibernated/session.d(218,33): Deprecation: function `std.exception.enforceEx!(CacheException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.
ddbctest ~master: building configuration "default"...
../../source/hibernated/metadata.d-mixin-3358(4064,43): Deprecation: function `std.exception.enforceEx!(MappingException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.`

**Comment by SingingBush** [comment]
fix has been merged
