### ISSUE TITLE
Implement Session Transactions Similar to Hibernate

### ISSUE THREAD

**Issue by vnayar** [buggins/hibernated#82]
Hibernate sessions can be used to begin, rollback, and commit SQL transactions as per its documentation: https://docs.jboss.org/hibernate/orm/6.4/javadocs/org/hibernate/Session.html

This is a known issue documented in the source: https://github.com/buggins/hibernated/blob/b810b14d75dddd5db463c91cafde7fc36757d965/source/hibernated/session.d#L66

**Comment by vnayar** [comment]
@SingingBush I'd like to take on this issue as time permits. In terms of strategy, what would be your recommendation for tackling this? Is it best to focus on the Hibernate interface and work entirely from the D code, or is the Java code of Hibernate being used as a reference? Or is there another project in another language that's the main reference?

**Comment by SingingBush** [comment]
that's fine. most of the commits I've made to the repo are to keep the code compiling with changes to the D compiler that have been made over the last few years. Vadim (@buggins) is the original author but as far as I know he no longer intends to work on D projects. As this project is supposed to be similar to Hibernate, it's worth looking at how things are done in Hibernate & JDBC ([DDBC](https://github.com/buggins/ddbc/) is the equivalent here) but it doesn't have to be identical. It should just feel familiar to users that have used Hibernate and be well documented and as easy to use. 

I suspect to implement something like `@Transactional` changes would need to be made to [DDBC](https://github.com/buggins/ddbc/) first. Whatever is done in DDBC to support transactions also needs to be done in a way that supports all supported databases

**Comment by vnayar** [comment]
Closed by #84 .
